In [1]:
import os
import numpy as np
from dataclasses import dataclass, fields
from VASP_job.code.main import VASP_job

import pandas as pd

Inputs

- positions
- magmoms
- element
- betah

In [2]:
atoms = pd.DataFrame({
   "elements"  : ["Mn", "Ga", "Mn"],
   "positions" : [[0, 0, 0], [0.5, 0.5, 0.5], [0.75, 0.75, 0.75]],
   "magmoms"   : [[0, 0, 2], [0, 0, 0], [0, 0, 2]],
   "betahs"    : [1.0, False, 1.0]
})
atoms = atoms.sort_values("elements")
atoms

elements           positions    magmoms betahs
1       Ga     [0.5, 0.5, 0.5]  [0, 0, 0]  False
0       Mn           [0, 0, 0]  [0, 0, 2]    1.0
2       Mn  [0.75, 0.75, 0.75]  [0, 0, 2]    1.0

In [3]:
len(atoms["elements"].tolist())

3

In [4]:
executable_path= "/home/emendive/workbench/work/from_claix/codes/VASP/vasp.5.4.4-flag4/bin"
potential_path = "/home/emendive/workbench/work/from_claix/codes/VASP/potentials/potpaw_PBE"
vasp = VASP_job(verbose="low", executable_path=executable_path, potential_path=potential_path)

In [5]:
vasp.prepare_calculation(atoms)

In [7]:
vasp.magnetism.betahs

[False, 1.0, 1.0]

In [9]:
vasp.magnetism.number_atoms = 10
vasp.magnetism.number_magnetic_atoms = 6
vasp.magnetism.betah = 100
vasp.magnetism.set_magmoms()

[array([0.57388937, 0.11412447, 2.94238451]),
 array([0.35708815, 0.04312387, 2.97836002]),
 array([0.16286577, 0.00886797, 2.99556274]),
 array([7.63986247e-02, 1.94684669e-03, 2.99902642e+00]),
 array([0.1143477 , 0.00436482, 2.9978168 ]),
 array([0.43696996, 0.06505845, 2.96729248]),
 array([0, 0, 0]),
 array([0, 0, 0]),
 array([0, 0, 0]),
 array([0, 0, 0])]

In [3]:
vasp.cwd

'/home/emendive/workbench/devel/gitclones/VASP_job/'

In [4]:
vasp.constr_INCAR_parameters.I_CONSTRAINED = '5'
vasp.write_inputs_and_job()

In [5]:
fields(vasp.job_parameters)[6].name.replace("_", "-")

'mem-per-cpu'

In [6]:
vasp.cwd = "/u/edmen"
print(vasp.cwd)
print(vasp.KPOINTS_file)

/u/edmen/
/u/edmen/KPOINTS


In [4]:
vasp.standard_INCAR_parameters

standard_INCAR_parameters(SYSTEM='my material #jobname', PREC='Accurate', ALGO='Fast', NPAR='8', LREAL='.FALSE.', LWAVE='.FALSE.', LCHARG='.TRUE.', LORBIT='10', ISMEAR='1', SIGMA='0.03', ISTART='0', ICHARG='2', ISPIN='2', ENCUT='500', EDIFF='1e-6', NELM='200', LMAXMIX='6', LNONCOLLINEAR='.TRUE.')

In [6]:
vasp.structure.kpoints = "1 1 1"
vasp.structure.kpoints

'1 1 1'

In [15]:
vasp.structure.elements = ["Ni"]
vasp.structure.potential_files.Ni = "Ni"

In [16]:
vasp.structure.write_POTCAR()
vasp.structure.write_KPOINTS()

In [11]:
vasp.structure.potential_files.Mn = 'Mn'
vasp.structure.potential_files.Mn

'Mn'

In [12]:
vasp.structure.write_POTCAR()